services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts/mlflow_server:/mlflow
